### ISSUE TITLE
JDK11 ?

### ISSUE THREAD

**Issue by xxscloud** [vy/quasar-maven-plugin#8]
JDK11 ?

/Users/xxscloud/code/jdk/jdk-11.0.5.jdk/Contents/Home/bin/java "-javaagent:/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar=63101:/Applications/IntelliJ IDEA.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath /Users/xxscloud/code/xf/id.zzxp/target/classes:/Users/xxscloud/.m2/repository/com/xxscloud/pudding/pudding-core/2.0.2/pudding-core-2.0.2.jar:/Users/xxscloud/.m2/repository/com/google/code/gson/gson/2.8.6/gson-2.8.6.jar:/Users/xxscloud/.m2/repository/org/apache/commons/commons-lang3/3.9/commons-lang3-3.9.jar:/Users/xxscloud/.m2/repository/org/apache/commons/commons-collections4/4.4/commons-collections4-4.4.jar:/Users/xxscloud/.m2/repository/org/apache/commons/commons-text/1.8/commons-text-1.8.jar:/Users/xxscloud/.m2/repository/commons-codec/commons-codec/1.13/commons-codec-1.13.jar:/Users/xxscloud/.m2/repository/org/apache/commons/commons-configuration2/2.6/commons-configuration2-2.6.jar:/Users/xxscloud/.m2/repository/commons-logging/commons-logging/1.2/commons-logging-1.2.jar:/Users/xxscloud/.m2/repository/org/apache/commons/commons-pool2/2.8.0/commons-pool2-2.8.0.jar:/Users/xxscloud/.m2/repository/commons-io/commons-io/1.3.2/commons-io-1.3.2.jar:/Users/xxscloud/.m2/repository/commons-beanutils/commons-beanutils/1.9.4/commons-beanutils-1.9.4.jar:/Users/xxscloud/.m2/repository/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar:/Users/xxscloud/.m2/repository/com/google/guava/guava/28.2-jre/guava-28.2-jre.jar:/Users/xxscloud/.m2/repository/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar:/Users/xxscloud/.m2/repository/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar:/Users/xxscloud/.m2/repository/org/checkerframework/checker-qual/2.10.0/checker-qual-2.10.0.jar:/Users/xxscloud/.m2/repository/com/google/errorprone/error_prone_annotations/2.3.4/error_prone_annotations-2.3.4.jar:/Users/xxscloud/.m2/repository/com/google/j2objc/j2objc-annotations/1.3/j2objc-annotations-1.3.jar:/Users/xxscloud/.m2/repository/joda-time/joda-time/2.10.4/joda-time-2.10.4.jar:/Users/xxscloud/.m2/repository/com/squareup/okhttp3/okhttp/4.2.2/okhttp-4.2.2.jar:/Users/xxscloud/.m2/repository/com/squareup/okio/okio/2.2.2/okio-2.2.2.jar:/Users/xxscloud/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib/1.3.50/kotlin-stdlib-1.3.50.jar:/Users/xxscloud/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib-common/1.3.50/kotlin-stdlib-common-1.3.50.jar:/Users/xxscloud/.m2/repository/org/jetbrains/annotations/13.0/annotations-13.0.jar:/Users/xxscloud/.m2/repository/org/projectlombok/lombok/1.18.10/lombok-1.18.10.jar:/Users/xxscloud/.m2/repository/org/slf4j/slf4j-api/2.0.0-alpha1/slf4j-api-2.0.0-alpha1.jar:/Users/xxscloud/.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar:/Users/xxscloud/.m2/repository/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3.jar:/Users/xxscloud/.m2/repository/org/codehaus/janino/janino/2.7.8/janino-2.7.8.jar:/Users/xxscloud/.m2/repository/org/codehaus/janino/commons-compiler/2.7.8/commons-compiler-2.7.8.jar:/Users/xxscloud/.m2/repository/io/vertx/vertx-core/3.8.4/vertx-core-3.8.4.jar:/Users/xxscloud/.m2/repository/io/netty/netty-common/4.1.42.Final/netty-common-4.1.42.Final.jar:/Users/xxscloud/.m2/repository/io/netty/netty-buffer/4.1.42.Final/netty-buffer-4.1.42.Final.jar:/Users/xxscloud/.m2/repository/io/netty/netty-transport/4.1.42.Final/netty-transport-4.1.42.Final.jar:/Users/xxscloud/.m2/repository/io/netty/netty-handler/4.1.42.Final/netty-handler-4.1.42.Final.jar:/Users/xxscloud/.m2/repository/io/netty/netty-codec/4.1.42.Final/netty-codec-4.1.42.Final.jar:/Users/xxscloud/.m2/repository/io/netty/netty-handler-proxy/4.1.42.Final/netty-handler-proxy-4.1.42.Final.jar:/Users/xxscloud/.m2/repository/io/netty/netty-codec-socks/4.1.42.Final/netty-codec-socks-4.1.42.Final.jar:/Users/xxscloud/.m2/repository/io/netty/netty-codec-http/4.1.42.Final/netty-codec-http-4.1.42.Final.jar:/Users/xxscloud/.m2/repository/io/netty/netty-codec-http2/4.1.42.Final/netty-codec-http2-4.1.42.Final.jar:/Users/xxscloud/.m2/repository/io/netty/netty-resolver/4.1.42.Final/netty-resolver-4.1.42.Final.jar:/Users/xxscloud/.m2/repository/io/netty/netty-resolver-dns/4.1.42.Final/netty-resolver-dns-4.1.42.Final.jar:/Users/xxscloud/.m2/repository/io/netty/netty-codec-dns/4.1.42.Final/netty-codec-dns-4.1.42.Final.jar:/Users/xxscloud/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.9.9/jackson-core-2.9.9.jar:/Users/xxscloud/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.9.9.1/jackson-databind-2.9.9.1.jar:/Users/xxscloud/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.9.0/jackson-annotations-2.9.0.jar:/Users/xxscloud/.m2/repository/io/vertx/vertx-web/3.8.4/vertx-web-3.8.4.jar:/Users/xxscloud/.m2/repository/io/vertx/vertx-web-common/3.8.4/vertx-web-common-3.8.4.jar:/Users/xxscloud/.m2/repository/io/vertx/vertx-auth-common/3.8.4/vertx-auth-common-3.8.4.jar:/Users/xxscloud/.m2/repository/io/vertx/vertx-bridge-common/3.8.4/vertx-bridge-common-3.8.4.jar:/Users/xxscloud/.m2/repository/io/vertx/vertx-mysql-client/3.8.4/vertx-mysql-client-3.8.4.jar:/Users/xxscloud/.m2/repository/io/vertx/vertx-sql-client/3.8.4/vertx-sql-client-3.8.4.jar:/Users/xxscloud/.m2/repository/io/vertx/vertx-rx-java2/3.8.4/vertx-rx-java2-3.8.4.jar:/Users/xxscloud/.m2/repository/io/reactivex/rxjava2/rxjava/2.2.12/rxjava-2.2.12.jar:/Users/xxscloud/.m2/repository/org/reactivestreams/reactive-streams/1.0.3/reactive-streams-1.0.3.jar:/Users/xxscloud/.m2/repository/io/vertx/vertx-rx-gen/3.8.4/vertx-rx-gen-3.8.4.jar:/Users/xxscloud/.m2/repository/io/vertx/vertx-codegen/3.8.4/vertx-codegen-3.8.4.jar:/Users/xxscloud/.m2/repository/org/mvel/mvel2/2.3.1.Final/mvel2-2.3.1.Final.jar:/Users/xxscloud/.m2/repository/io/vertx/vertx-sync/3.8.4/vertx-sync-3.8.4.jar:/Users/xxscloud/.m2/repository/co/paralleluniverse/quasar-core/0.7.10/quasar-core-0.7.10-jdk8.jar:/Users/xxscloud/.m2/repository/com/esotericsoftware/kryo/4.0.0/kryo-4.0.0.jar:/Users/xxscloud/.m2/repository/com/esotericsoftware/reflectasm/1.11.3/reflectasm-1.11.3.jar:/Users/xxscloud/.m2/repository/com/esotericsoftware/minlog/1.3.0/minlog-1.3.0.jar:/Users/xxscloud/.m2/repository/org/objenesis/objenesis/2.2/objenesis-2.2.jar:/Users/xxscloud/.m2/repository/de/javakaffee/kryo-serializers/0.42/kryo-serializers-0.42.jar com.zizaixp.id.Application
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions prior to 1.8.
SLF4J: Ignoring binding found at [jar:file:/Users/xxscloud/.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#ignoredBindings for an explanation.
QUASAR WARNING: Quasar Java Agent isn't running. If you're using another instrumentation method you can ignore this message; otherwise, please refer to the Getting Started section in the Quasar documentation.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by co.paralleluniverse.concurrent.util.ThreadAccess (file:/Users/xxscloud/.m2/repository/co/paralleluniverse/quasar-core/0.7.10/quasar-core-0.7.10-jdk8.jar) to constructor java.lang.ThreadLocal$ThreadLocalMap(java.lang.ThreadLocal,java.lang.Object)
WARNING: Please consider reporting this to the maintainers of co.paralleluniverse.concurrent.util.ThreadAccess
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
io.vertx.core.VertxException: java.lang.IllegalThreadStateException: Method called not from within a fiber
	at io.vertx.ext.sync.Sync.awaitResult(Sync.java:50)
	at com.zizaixp.id.verticle.IndexVerticle.start(IndexVerticle.java:32)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$9(DeploymentManager.java:556)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalThreadStateException: Method called not from within a fiber
	at co.paralleluniverse.fibers.FiberAsync.requestSync(FiberAsync.java:300)
	at co.paralleluniverse.fibers.FiberAsync.runSync(FiberAsync.java:259)
	at co.paralleluniverse.fibers.FiberAsync.run(FiberAsync.java:112)
	at io.vertx.ext.sync.Sync.awaitResult(Sync.java:48)
	... 11 more

**Comment by vy** [comment]
PR?

**Comment by xxscloud** [comment]
Sorry, I got it wrong. Recently I was researching the use of JDK11, which caused me a headache. Now I am back to JDK8. I am ready to give up the research.
